{% set version = "0.1.0" %}
{% set name = "timeseries" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../


requirements:
  host:
    - numpy
    - pip
    - python
  run:
    - scipy
    - numpy
    - python

about:
  home: "https://github.com/goiosunsw/timeseries.git"
  license: "GNU Lesser General Public v3 or later (LGPLv3+)"
  license_family: "LGPL"
  license_file: ""
  summary: "Time series objects and utilities"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - goiosunsw
